#指定端口号
server:
  port: 9527
  servlet.context-path: /

Spring:
  datasource:
    username: root
    password: 3141592653
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
    mysqldriverclassname: com.mysql.jdbc.Driver
